dataset : [
            "/tmp-network/user/rdeffaye/mslr/10K/CoCM_mismatch-plackettluce-bm25/",
            "/tmp-network/user/rdeffaye/mslr/10K/CoCM_mismatch-plackettluce-lambdamart/",
            "/tmp-network/user/rdeffaye/mslr/10K/CoCM_mismatch-plackettluceoracle/",
            "/tmp-network/user/rdeffaye/mslr/10K/CoCM-plackettluce-lambdamart/",
            "/tmp-network/user/rdeffaye/mslr/10K/CoCM-plackettluce-bm25/",
            "/tmp-network/user/rdeffaye/mslr/10K/CoCM-plackettluceoracle/",
            "/tmp-network/user/rdeffaye/mslr/10K/DBN-plackettluce-lambdamart/",
            "/tmp-network/user/rdeffaye/mslr/10K/DBN-plackettluce-bm25/",
            "/tmp-network/user/rdeffaye/mslr/10K/DBN-plackettluceoracle/"
]

cp_name : [
            "PBM_ImmediateStateLearner_onlyquery64_itemembedd64_seed2021.ckpt",
            "PBM_ImmediateStateLearner_onlyquery64_itemembedd64_seed4987.ckpt",
            "PBM_ImmediateStateLearner_onlyquery64_itemembedd64_seed24657.ckpt",
            "PBM_ImmediateStateLearner_onlyquery64_itemembedd64_seed300029.ckpt",
            "PBM_ImmediateStateLearner_onlyquery64_itemembedd64_seed315567.ckpt",
            "PBM_ImmediateStateLearner_onlyquery64_itemembedd64_seed2451.ckpt",
            "PBM_ImmediateStateLearner_onlyquery64_itemembedd64_seed3272447.ckpt",
            "PBM_ImmediateStateLearner_onlyquery64_itemembedd64_seed23577.ckpt",
            "PBM_ImmediateStateLearner_onlyquery64_itemembedd64_seed3241591.ckpt",
            "PBM_ImmediateStateLearner_onlyquery64_itemembedd64_seed23444.ckpt",

            "UBM_ImmediateStateLearner_onlyquery64_itemembedd64_seed2021.ckpt",
            "UBM_ImmediateStateLearner_onlyquery64_itemembedd64_seed4987.ckpt",
            "UBM_ImmediateStateLearner_onlyquery64_itemembedd64_seed24657.ckpt",
            "UBM_ImmediateStateLearner_onlyquery64_itemembedd64_seed300029.ckpt",
            "UBM_ImmediateStateLearner_onlyquery64_itemembedd64_seed315567.ckpt",
            "UBM_ImmediateStateLearner_onlyquery64_itemembedd64_seed2451.ckpt",
            "UBM_ImmediateStateLearner_onlyquery64_itemembedd64_seed3272447.ckpt",
            "UBM_ImmediateStateLearner_onlyquery64_itemembedd64_seed23577.ckpt",
            "UBM_ImmediateStateLearner_onlyquery64_itemembedd64_seed3241591.ckpt",
            "UBM_ImmediateStateLearner_onlyquery64_itemembedd64_seed23444.ckpt",

            "DBN_ImmediateStateLearner_onlyquery64_itemembedd64_seed2021.ckpt",
            "DBN_ImmediateStateLearner_onlyquery64_itemembedd64_seed4987.ckpt",
            "DBN_ImmediateStateLearner_onlyquery64_itemembedd64_seed24657.ckpt",
            "DBN_ImmediateStateLearner_onlyquery64_itemembedd64_seed300029.ckpt",
            "DBN_ImmediateStateLearner_onlyquery64_itemembedd64_seed315567.ckpt",
            "DBN_ImmediateStateLearner_onlyquery64_itemembedd64_seed2451.ckpt",
            "DBN_ImmediateStateLearner_onlyquery64_itemembedd64_seed3272447.ckpt",
            "DBN_ImmediateStateLearner_onlyquery64_itemembedd64_seed23577.ckpt",
            "DBN_ImmediateStateLearner_onlyquery64_itemembedd64_seed3241591.ckpt",
            "DBN_ImmediateStateLearner_onlyquery64_itemembedd64_seed23444.ckpt",

            "ARM_absolute_ImmediateStateLearner_onlyquery64_itemembedd64_seed2021.ckpt",
            "ARM_absolute_ImmediateStateLearner_onlyquery64_itemembedd64_seed4987.ckpt",
            "ARM_absolute_ImmediateStateLearner_onlyquery64_itemembedd64_seed24657.ckpt",
            "ARM_absolute_ImmediateStateLearner_onlyquery64_itemembedd64_seed300029.ckpt",
            "ARM_absolute_ImmediateStateLearner_onlyquery64_itemembedd64_seed315567.ckpt",
            "ARM_absolute_ImmediateStateLearner_onlyquery64_itemembedd64_seed2451.ckpt",
            "ARM_absolute_ImmediateStateLearner_onlyquery64_itemembedd64_seed3272447.ckpt",
            "ARM_absolute_ImmediateStateLearner_onlyquery64_itemembedd64_seed23577.ckpt",
            "ARM_absolute_ImmediateStateLearner_onlyquery64_itemembedd64_seed3241591.ckpt",
            "ARM_absolute_ImmediateStateLearner_onlyquery64_itemembedd64_seed23444.ckpt",

            "NEHBM_ImmediateStateLearner_onlyquery64_itemembedd64_seed2021.ckpt",
            "NEHBM_ImmediateStateLearner_onlyquery64_itemembedd64_seed4987.ckpt",
            "NEHBM_ImmediateStateLearner_onlyquery64_itemembedd64_seed24657.ckpt",
            "NEHBM_ImmediateStateLearner_onlyquery64_itemembedd64_seed300029.ckpt",
            "NEHBM_ImmediateStateLearner_onlyquery64_itemembedd64_seed315567.ckpt",
            "NEHBM_ImmediateStateLearner_onlyquery64_itemembedd64_seed2451.ckpt",
            "NEHBM_ImmediateStateLearner_onlyquery64_itemembedd64_seed3272447.ckpt",
            "NEHBM_ImmediateStateLearner_onlyquery64_itemembedd64_seed23577.ckpt",
            "NEHBM_ImmediateStateLearner_onlyquery64_itemembedd64_seed3241591.ckpt",
            "NEHBM_ImmediateStateLearner_onlyquery64_itemembedd64_seed23444.ckpt",

            "NCM_GRU64_ImmediateStateLearner_onlyquery64_itemembedd64_seed2021.ckpt",
            "NCM_GRU64_ImmediateStateLearner_onlyquery64_itemembedd64_seed4987.ckpt",
            "NCM_GRU64_ImmediateStateLearner_onlyquery64_itemembedd64_seed24657.ckpt",
            "NCM_GRU64_ImmediateStateLearner_onlyquery64_itemembedd64_seed300029.ckpt",
            "NCM_GRU64_ImmediateStateLearner_onlyquery64_itemembedd64_seed315567.ckpt",
            "NCM_GRU64_ImmediateStateLearner_onlyquery64_itemembedd64_seed2451.ckpt",
            "NCM_GRU64_ImmediateStateLearner_onlyquery64_itemembedd64_seed3272447.ckpt",
            "NCM_GRU64_ImmediateStateLearner_onlyquery64_itemembedd64_seed23577.ckpt",
            "NCM_GRU64_ImmediateStateLearner_onlyquery64_itemembedd64_seed3241591.ckpt",
            "NCM_GRU64_ImmediateStateLearner_onlyquery64_itemembedd64_seed23444.ckpt"
]